"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = ["status"]

[[--scope]]
--when.repositories = ["/Users/luthenwald"]

[--scope.user]
name = "luthenwald"
email = "luthenwald@pm.me"

[[--scope]]
--when.repositories = ["/Users/chanhuizhihou"]

[--scope.user]
name = "jonathanyale"
email = "jonathanyale@pm.me"

