"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
diff-editor = "meld" 
merge-editor = "meld"
default-command = ["st"]

[aliases]
ll = ["log", "-T", "log_with_files"]
cm = ["log", "-T", "log_compact"]

[revset-aliases]
'recent_work' = 'ancestors(visible_heads(), 3) & mutable()'

[template-aliases]
log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        bookmarks,
        tags,
        working_copies,
        if(git_head, label("git_head", "HEAD")),
        if(conflict, label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(signature)),
        if(!description && !empty, "\n" ++ diff.summary()),
      ) ++ "\n",
    ),
  )
)
'''
log_with_files = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      format_short_commit_header(self) ++ "\n",
      separate(" ",
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
      if(self.contained_in("recent_work"), diff.summary()),
    ),
  )
)
'''
log_json_stream = '''
  "{" ++ 
    "change_id".escape_json() ++ ": " ++ stringify(change_id).escape_json() ++ ", " ++ 
    "author".escape_json() ++ ": " ++ stringify(author).escape_json() ++
  "}\n"
'''
[[--scope]]
--when.repositories = ["/Users/luthenwald"]

[--scope.user]
name = "luthenwald"
email = "luthenwald@pm.me"

[[--scope]]
--when.repositories = ["/Users/chanhuizhihou"]

[--scope.user]
name = "jonathanyale"
email = "jonathanyale@pm.me"

[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
pager = "delta"
diff-formatter = ":git"
