"ui.background" = { fg = "white" }
"ui.background.separator" = { fg = "gray" }
"ui.text" = { fg = "light-gray" }
"ui.text.focus" = { fg = "white" }
"ui.menu" = { fg = "white" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "light-gray" }
"ui.linenr" = { modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.popup" = { fg = "white" }
"ui.window" = { fg = "gray" }
"ui.selection" = { bg = "gray" }
"comment" = { fg = "light-gray", modifiers = ["italic"] }
"doc.comment" = { fg = "light-gray", modifiers = ["italic"] }
"ui.help" = { fg = "light-gray" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "light-yellow", underline = { color = "light-yellow", style = "line" } }
"ui.cursor.primary" = { modifiers = ["reversed", "slow_blink"] }
"ui.cursor.secondary" = { modifiers = ["reversed"] }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.indent-guide" = "gray"
"ui.virtual.inlay-hint" = { fg = "white", bg = "gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "white", bg = "gray" }
"ui.virtual.inlay-hint.type" = { fg = "white", bg = "gray" }
"ui.virtual.wrap" = "gray"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }

"variable" = "light-red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attribute" = "yellow"
"type" = { fg = "light-yellow", modifiers = ["bold"] }
"string" = { fg = "light-green" }
"variable.other.member" = { fg = "green" }
"constant.character.escape" = { fg = "light-cyan" }
"function" = { fg = "light-blue", modifiers = ["bold"] }
"constructor" = { fg = "light-blue" }
"special" = { fg = "light-blue" }
"keyword" = { fg = "light-magenta", modifiers = ["italic"] }
"label" = { fg = "light-magenta" }
"namespace" = { fg = "light-magenta" }

"markup.heading" = { fg = "light-blue", modifiers = ["bold"] }
"markup.list" = { fg = "light-red" }
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "yellow", underline = { color = "yellow", style = "line" } }
"markup.link.text" = { fg = "light-red" }
"markup.quote" = { fg = "light-cyan" }
"markup.raw" = { fg = "green" }
"markup.normal" = { fg = "blue" }
"markup.insert" = { fg = "green" }
"markup.select" = { fg = "magenta" }

"diff.plus" = { fg = "light-green", modifiers = ["bold"] }
"diff.delta" = { fg = "light-blue", modifiers = ["bold"] }
"diff.delta.moved" = { fg = "blue" }
"diff.minus" = { fg = "light-red", modifiers = ["bold"] }

"ui.gutter" = { fg = "gray" }
"info" = { fg = "light-blue", modifiers = ["bold"] }
"hint" = "light-gray"
"debug" = "light-gray"
"warning" = { fg = "light-yellow", modifiers = ["bold"] }
"error" = { fg = "light-red", modifiers = ["bold"] }
